# Generated by Django 4.2.4 on 2023-08-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='이미지')),
                ('name', models.CharField(max_length=25, verbose_name='메뉴명')),
                ('price', models.IntegerField(default=10000, verbose_name='가격')),
                ('calorie', models.FloatField(default=100.5, verbose_name='칼로리')),
            ],
        ),
    ]
