# Generated by Django 4.2.4 on 2023-08-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='이미지')),
                ('name', models.CharField(max_length=25, verbose_name='메뉴명')),
                ('price', models.IntegerField(default=10000, verbose_name='가격')),
                ('calorie', models.FloatField(default=100.5, verbose_name='칼로리')),
            ],
        ),
        migrations.CreateModel(
            name='TestMenuTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='메뉴명')),
                ('price', models.IntegerField(default=5000, verbose_name='가격')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='이미지')),
                ('info', models.TextField(verbose_name='정보')),
                ('Bulgogi', models.BooleanField(default=False, verbose_name='불고기')),
                ('Chicken', models.BooleanField(default=False, verbose_name='치킨')),
                ('Shrimp', models.BooleanField(default=False, verbose_name='새우')),
                ('Beef', models.BooleanField(default=False, verbose_name='소고기')),
                ('Bacon', models.BooleanField(default=False, verbose_name='베이컨')),
                ('Squid', models.BooleanField(default=False, verbose_name='오징어')),
                ('Cheese', models.BooleanField(default=False, verbose_name='치즈')),
                ('Tomato', models.BooleanField(default=False, verbose_name='토마토')),
            ],
        ),
    ]
