# Generated by Django 4.2.4 on 2023-08-11 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='test_Menu_Set',
            fields=[
                ('menu_name', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('weight', models.IntegerField(null=True)),
                ('calories', models.IntegerField(null=True)),
                ('protein', models.IntegerField(null=True)),
                ('sodium', models.IntegerField(null=True)),
                ('sugars', models.IntegerField(null=True)),
                ('saturated_fat', models.IntegerField(null=True)),
                ('caffeine', models.IntegerField(null=True)),
                ('milk', models.IntegerField(null=True)),
                ('pork', models.IntegerField(null=True)),
                ('tomato', models.IntegerField(null=True)),
                ('beef', models.IntegerField(null=True)),
                ('egg', models.IntegerField(null=True)),
                ('squid', models.IntegerField(null=True)),
                ('lettuce', models.IntegerField(null=True)),
                ('mayo', models.IntegerField(null=True)),
                ('sliced_cheese', models.IntegerField(null=True)),
                ('shredded_cheese', models.IntegerField(null=True)),
                ('pickle', models.IntegerField(null=True)),
                ('jalapeno', models.IntegerField(null=True)),
                ('whole_shrimp', models.IntegerField(null=True)),
                ('bacon', models.IntegerField(null=True)),
                ('onion', models.IntegerField(null=True)),
                ('bulgogi', models.IntegerField(null=True)),
                ('barbecue', models.IntegerField(null=True)),
                ('ketchup', models.IntegerField(null=True)),
                ('diablo', models.IntegerField(null=True)),
                ('spicy_tomato', models.IntegerField(null=True)),
                ('cheese', models.IntegerField(null=True)),
                ('tartar', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='menu',
            name='kkk',
        ),
    ]
