# Generated by Django 4.2.4 on 2023-08-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmenutable',
            name='Bacon',
            field=models.BooleanField(default=False, null=True, verbose_name='베이컨'),
        ),
        migrations.AlterField(
            model_name='testmenutable',
            name='Beef',
            field=models.BooleanField(default=False, null=True, verbose_name='소고기'),
        ),
        migrations.AlterField(
            model_name='testmenutable',
            name='Bulgogi',
            field=models.BooleanField(default=False, null=True, verbose_name='불고기'),
        ),
        migrations.AlterField(
            model_name='testmenutable',
            name='Cheese',
            field=models.BooleanField(default=False, null=True, verbose_name='치즈'),
        ),
        migrations.AlterField(
            model_name='testmenutable',
            name='Chicken',
            field=models.BooleanField(default=False, null=True, verbose_name='치킨'),
        ),
        migrations.AlterField(
            model_name='testmenutable',
            name='Shrimp',
            field=models.BooleanField(default=False, null=True, verbose_name='새우'),
        ),
        migrations.AlterField(
            model_name='testmenutable',
            name='Squid',
            field=models.BooleanField(default=False, null=True, verbose_name='오징어'),
        ),
        migrations.AlterField(
            model_name='testmenutable',
            name='Tomato',
            field=models.BooleanField(default=False, null=True, verbose_name='토마토'),
        ),
    ]
