# Generated by Django 4.2.4 on 2023-08-13 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0002_alter_testmenutable_bacon_alter_testmenutable_beef_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmenutable',
            name='Cold',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='testmenutable',
            name='Hot',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='testmenutable',
            name='Prok',
            field=models.BooleanField(default=False, null=True, verbose_name='돼지고기'),
        ),
        migrations.AddField(
            model_name='testmenutable',
            name='Spicy',
            field=models.BooleanField(default=False, null=True, verbose_name='맵기'),
        ),
        migrations.AddField(
            model_name='testmenutable',
            name='Whopper',
            field=models.BooleanField(default=False, null=True, verbose_name='와퍼'),
        ),
    ]
