# Generated by Django 4.2.4 on 2023-08-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0003_testmenutable_cold_testmenutable_hot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmenutable',
            name='info',
            field=models.TextField(default='맛있다.', verbose_name='정보'),
        ),
    ]
