# Generated by Django 4.2.4 on 2023-08-14 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0004_alter_testmenutable_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmenutable',
            name='test_col',
            field=models.TextField(default='연습용', verbose_name='test_1'),
        ),
    ]
