# Generated by Django 4.2.4 on 2023-08-14 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0005_testmenutable_test_col'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testmenutable',
            name='test_col',
        ),
    ]
