# Generated by Django 4.2.4 on 2023-08-15 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0006_remove_testmenutable_test_col'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=25, verbose_name='메뉴명')),
                ('price', models.IntegerField(default=5000, verbose_name='가격')),
                ('image', models.CharField(max_length=50, verbose_name='이미지')),
                ('info', models.TextField(default='맛있다.', verbose_name='정보')),
                ('rank', models.IntegerField(default=99, verbose_name='인기순위')),
                ('spicy', models.IntegerField(default=0, verbose_name='맵기')),
                ('calories', models.IntegerField(default=0, verbose_name='영양성분 : 칼로리')),
                ('protein', models.IntegerField(default=0, verbose_name='영양성분 : 단백질')),
                ('sodium', models.IntegerField(default=0, verbose_name='영양성분 : 나트륨')),
                ('sugars', models.FloatField(default=0, verbose_name='영양성분 : 설탕')),
                ('saturated_fat', models.FloatField(default=0, verbose_name='영양성분 : 포화지방')),
                ('Amilk', models.BooleanField(default=False, null=True, verbose_name='알레르기 : 우유')),
                ('AChicken', models.BooleanField(default=False, null=True, verbose_name='알레르기 : 치킨')),
                ('Apork', models.BooleanField(default=False, null=True, verbose_name='알레르기 : 돼지')),
                ('Abeef', models.BooleanField(default=False, null=True, verbose_name='알레르기 : 소')),
                ('Aegg', models.BooleanField(default=False, null=True, verbose_name='알레르기 : 난류')),
                ('Asquid', models.BooleanField(default=False, null=True, verbose_name='알레르기 : 오징어')),
                ('ATomato', models.BooleanField(default=False, null=True, verbose_name='알레르기 : 토마토')),
                ('Aclam', models.BooleanField(default=False, null=True, verbose_name='알레르기 : 조개')),
                ('Ashrimp', models.BooleanField(default=False, null=True, verbose_name='알레르기 : 새우')),
                ('sliced_cheese', models.IntegerField(default=0, verbose_name='재료 : 얇게 썬 치즈')),
                ('shredded_cheese', models.IntegerField(default=0, verbose_name='재료 : 잘게 썬 치즈')),
                ('pickle', models.IntegerField(default=0, verbose_name='재료 : 피클')),
                ('jalapeno', models.IntegerField(default=0, verbose_name='재료 : 할라피뇨')),
                ('whole_shrimp', models.IntegerField(default=0, verbose_name='재료 : 통새우')),
                ('bacon', models.IntegerField(default=0, verbose_name='재료 : 베이컨')),
                ('lettuce', models.IntegerField(default=0, verbose_name='재료 : 상추')),
                ('onion', models.IntegerField(default=0, verbose_name='재료 : 양파')),
                ('hashbrown', models.IntegerField(default=0, verbose_name='재료 : 해쉬브라운')),
                ('mayo', models.BooleanField(default=False, null=True, verbose_name='소스 : 마요네즈')),
                ('bulgogi', models.BooleanField(default=False, null=True, verbose_name='소스 : 불고기')),
                ('barbecue', models.BooleanField(default=False, null=True, verbose_name='소스 : 바비큐 ')),
                ('ketchup', models.BooleanField(default=False, null=True, verbose_name='소스 : 캐첩')),
                ('diablo', models.BooleanField(default=False, null=True, verbose_name='소스 : 디아블로 ')),
                ('spicy_tomato', models.BooleanField(default=False, null=True, verbose_name='소스 : 매운 토마토 ')),
                ('cheese', models.BooleanField(default=False, null=True, verbose_name='소스 : 치즈 ')),
                ('tartar', models.BooleanField(default=False, null=True, verbose_name='소스 : 타르타르 ')),
                ('baconjam', models.BooleanField(default=False, null=True, verbose_name='소스 : 베이컨잼')),
                ('mustard', models.BooleanField(default=False, null=True, verbose_name='소스 : 머스타드')),
                ('Pbeef', models.IntegerField(default=0, verbose_name='패티 : 소고기')),
                ('Pshrimp', models.IntegerField(default=0, verbose_name='패티 : 새우')),
                ('Pchicken', models.IntegerField(default=0, verbose_name='패티 : 치킨')),
                ('Psteak', models.IntegerField(default=0, verbose_name='패티 : 스테이크')),
            ],
        ),
        migrations.DeleteModel(
            name='TestMenuTable',
        ),
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/BURGERKING_MENU/Burger/', verbose_name='이미지'),
        ),
    ]
