# Generated by Django 4.2.4 on 2023-08-15 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0008_rename_achicken_menutable_a_chicken_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menutable',
            old_name='A_Chicken',
            new_name='A_chicken',
        ),
        migrations.RenameField(
            model_name='menutable',
            old_name='A_Tomato',
            new_name='A_tomato',
        ),
    ]
