# Generated by Django 4.2.4 on 2023-08-15 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0010_alter_menutable_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menutable',
            name='I_garlic_chip',
            field=models.IntegerField(default=0, verbose_name='재료 : 갈릭칩'),
        ),
        migrations.AddField(
            model_name='menutable',
            name='I_tomato',
            field=models.IntegerField(default=0, verbose_name='재료 : 토마토'),
        ),
    ]
