# Generated by Django 4.2.4 on 2023-08-15 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0011_menutable_i_garlic_chip_menutable_i_tomato'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menutable',
            old_name='image',
            new_name='M_image',
        ),
        migrations.RenameField(
            model_name='menutable',
            old_name='info',
            new_name='M_info',
        ),
        migrations.RenameField(
            model_name='menutable',
            old_name='menu_name',
            new_name='M_menu_name',
        ),
        migrations.RenameField(
            model_name='menutable',
            old_name='price',
            new_name='M_price',
        ),
        migrations.RenameField(
            model_name='menutable',
            old_name='rank',
            new_name='M_rank',
        ),
        migrations.RenameField(
            model_name='menutable',
            old_name='spicy',
            new_name='M_spicy',
        ),
    ]
