col_dict = {
    'I_sliced_cheese 1' : '치즈가 들어간',
    'I_sliced_cheese 0' : '치즈가 안들어간',
    'I_whole_shrimp 1' : '통새우가 들어간',
    'I_whole_shrimp 0' : '통새우가 안들어간',
    'I_tomato 1' : '토마토가 들어간',
    'I_tomato 0' : '토마토가 안들어간',
    'I_shredded_cheese 1' : '슈레드 치즈가 들어간',
    'I_shredded_cheese 0' : '슈레드 치즈가 안들어간',
    'I_pickle 1' : '피클이 들어간',
    'I_pickle 0' : '피클이 안들어간',
    'I_onion 1' : '양파가 들어간',
    'I_onion 0' : '양파가 안들어간',
    'I_lettuce 1' : '양상추가 들어간',
    'I_lettuce 0' : '양상추가 안들어간',
    'I_jalapeno 1' : '할라피뇨가 들어간',
    'I_jalapeno 0' : '할라피뇨가 안들어간',
    'I_hashbrown 1' : '해쉬브라운이 들어간',
    'I_hashbrown 0' : '해쉬브라운이 안들어간',
    'I_garlic_chip 1' : '갈릭칩이 들어간',
    'I_garlic_chip 0' : '갈릭칩이 안들어간',
    'I_bacon 1' : '베이컨이 들어간',
    'I_bacon 0' : '베이컨이 안들어간',
    'A' : '알레르기 관련정보',
    'N' : '영샹성분 관련정보',
    'P_steak 1' : '스테이크 패티가 들어간',
    'P_steak 0' : '스테이크 패티가 안들어간',
    'P_shrimp 1' : '새우 패티가 들어간',
    'P_shrimp 0' : '새우 패티가 들어간',
    'P_chicken 1' : '치킨 패티가 들어간',
    'P_chicken 0' : '치킨 패티가 들어간',
    'P_beef 1' : '비프 패티가 들어간',
    'P_beef 0' : '비프 패티가 들어간',
    'menu_name 1' : '메뉴는',
    'M' : '햄버거',
    '5' : '노인남성',
    '0' : '추천',
    'asc' : '낮은',
    'desc' : '높은',
    'N_calories' : '칼로리',
    'or' : '',
    'S_mayo 1' : '마요네즈 들어간',
    'S_mayo 0' : '마요네즈 안들어간',
    'S_bulgogi 1': '불고기 들어간',
    'S_bulgogi 0': '불고기 안들어간',
    'S_barbecue 1' : '바비큐 들어간',
    'S_barbecue 0' : '바비큐 안들어간',
    'S_ketchup 1' : '케찹 들어간',
    'S_ketchup 0' : '케찹 안들어간',
    'S_diablo 1' : '디아블로 들어간',
    'S_diablo 0' : '디아블로 안들어간',
    'S_spicy_tomato 1':'스파이시 토마토 들어간',
    'S_spicy_tomato 0':'스파이시 토마토 안들어간',
    'S_cheese 1' : '치즈소스 들어간',
    'S_cheese 0' : '치즈소스 안들어간',
    'S_tartar 1':'타르타르 들어간',
    'S_tartar 0':'타르타르 안들어간',
    'S_baconjam 1':'베이컨 잼 들어간',
    'S_baconjam 0':'베이컨 잼 안들어간',
    'S_mustard 1' :' 머스타드 들어간',
    'S_mustard 0' :' 머스타드 안들어간',
    '3' : '젊은 남성',
    '4' : '젊은 여성',
    '6' : '노인 여성',
    '7' : '젊은이',
    '8' : '어르신',
    '9' : '여름',
    '10' : '겨울',
    '11' : '기타',
    'spicy 1' : '매운',
    'spicy 0' : '안매운',
    'N_protein': '단백질',
    'menu_name 와퍼': '와퍼',
    'menu_name 와퍼주니어': '와퍼주니어',
    'menu_name 갈릭불고기와퍼': '갈릭불고기와퍼',
    'menu_name 더블오리지날치즈버거': '더블오리지날치즈버거',
    'menu_name 더블비프불고기': '더블비프불고기',
    'menu_name 롱치킨버거': '롱치킨버거',
    'menu_name 몬스터와퍼': '몬스터와퍼',
    'menu_name 몬스터X': '몬스터X',
    'menu_name 불고기와퍼': '불고기와퍼',
    'menu_name 불고기와퍼주니어': '불고기와퍼주니어',
    'menu_name 블랙바비큐와퍼': '블랙바비큐와퍼',
    'menu_name 블랙바비큐콰트로치즈와퍼': '블랙바비큐콰트로치즈와퍼',
    'menu_name 비프불고기버거': '비프불고기버거',
    'menu_name 비프&슈림프버거': '비프&슈림프버거',
    'menu_name 치즈버거': '치즈버거',
    'menu_name 치즈와퍼': '치즈와퍼',
    'menu_name 치즈와퍼주니어': '치즈와퍼주니어',
    'menu_name 치킨버거': '치킨버거',
    'menu_name 치킨킹': '치킨킹',
    'menu_name 치킨킹BLT': '치킨킹BLT',
    'menu_name 콰트로치즈와퍼': '콰트로치즈와퍼',
    'menu_name 콰트로치즈와퍼주니어': '콰트로치즈와퍼주니어',
    'menu_name 통새우슈림프버거': '통새유슈림프버거',
    'menu_name 통새우와퍼': '통새우와퍼',
    'menu_name 통새우와퍼주니어': '통새우와퍼주니어',
    'menu_name 헬로 디아블로 와퍼': '헬로 디아블로 와퍼',
    'menu_name 헬로 릴리트 와퍼': '헬로 릴리트 와퍼',
    'menu_name 헬로 이나리우스 와퍼': '헬로 이나리우스 와퍼',
    'menu_name 슈림프버거': '슈림프버거',
    'menu_name 해쉬브라운': '해쉬브라운',
    'menu_name 21치즈스틱': '21치즈스틱',
    'menu_name 주니어': '주니어',
    'menu_name 너겟킹': '너겟킹',
    'menu_name 어니언링': '어니언링',
    'menu_name 바삭킹': '바삭킹',
    'menu_name 헬로': '헬로',
    'menu_name 쉐이킹프라이': '쉐이킹프라이',
    'menu_name 크리미모짜볼': '크리미모짜볼',
    'menu_name 코코넛슈림프': '코코넛슈림프',
    'menu_name 치즈프라이': '치즈프라이',
    'menu_name 프렌치프라이': '프렌치프라이',
    'menu_name 콘샐러드': '콘샐러드',
    'menu_name 디아블로소스': '디아블로소스',
    'menu_name 망고 선데이': '망고 선데이',
    'menu_name 초코 망고 선데이': '초코 망고 선데이',
    'menu_name 레드애플맛제로': '레드애플맛제로',
    'menu_name 레몬라임맛제로': '레몬라임맛제로',
    'menu_name 컵 망고 아이스크림': '컵 망고 아이스크림',
    'menu_name 아메리카노': '아메리카노',
    'menu_name 아이스 아메리카노': '아이스 아메리카노',
    'menu_name 핫초코': '핫초코',
    'menu_name 아이스초코': '아이스초코',
    'menu_name 코카콜라': '코카콜라',
    'menu_name 코카콜라_제로': '코카콜라_제로',
    'menu_name 스프라이트': '스프라이트_제로',
    'menu_name 미닛메이드_오렌지': '미닛메이드 오렌지',
    'menu_name 순수(미네랄워터)': '순수(미네랄워터)',
    'menu_name 제로': '제로',
    'menu_name 이나리우스': '이나리우스',
    'DD': '음료 & 디저트',
    
    }
    




# 'A_tomato' : '토마토 알레르기'
# 'A_tomato' : '토마토 알레르기'
# 'A_squid' :  '오징어 알레르기'
# 'A_squid' :  '오징어 알레르기'
# 'A_shrimp' : '새우 알레르기'
# 'A_shrimp' : '새우 알레르기'
# 'A_pork' : '돼지고기 알레르기'
# 'A_pork' : '돼지고기 알레르기'
# 'A_milk' : '우유 알레르기'
# 'A_milk' : '우유 알레르기'
# 'A_egg' : '난류 알레르기'
# 'A_egg' : '난류 알레르기'
# 'A_clam' : '조개 알레르기'
# 'A_clam' : '조개 알레르기'
# 'A_chicken' : '치킨 알레르기'
# 'A_chicken' : '치킨 알레르기'
# 'A_beef' : '소고기 알레르기'
# 'A_beef' : '소고기 알레르기'
